// <auto-generated />
using System;
using Escalouve.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Escalouve.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240227214226_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Escalouve.Domain.Entities.Escala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Escalas");
                });

            modelBuilder.Entity("Escalouve.Domain.Entities.Escalado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EscalaId")
                        .HasColumnType("integer");

                    b.Property<int>("InstrumentoId")
                        .HasColumnType("integer");

                    b.Property<int>("IntegranteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EscalaId");

                    b.HasIndex("InstrumentoId");

                    b.HasIndex("IntegranteId");

                    b.ToTable("Escalados");
                });

            modelBuilder.Entity("Escalouve.Domain.Entities.Instrumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Instrumentos");
                });

            modelBuilder.Entity("Escalouve.Domain.Entities.Integrante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Integrantes");
                });

            modelBuilder.Entity("Escalouve.Domain.Entities.IntegranteInstrumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InstrumentoId")
                        .HasColumnType("integer");

                    b.Property<int>("IntegranteId")
                        .HasColumnType("integer");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentoId");

                    b.HasIndex("IntegranteId");

                    b.ToTable("IntegranteInstrumento");
                });

            modelBuilder.Entity("Escalouve.Domain.Entities.Escalado", b =>
                {
                    b.HasOne("Escalouve.Domain.Entities.Escala", "Escala")
                        .WithMany("Escalados")
                        .HasForeignKey("EscalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Escalouve.Domain.Entities.Instrumento", "Instrumento")
                        .WithMany()
                        .HasForeignKey("InstrumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Escalouve.Domain.Entities.Integrante", "Integrante")
                        .WithMany()
                        .HasForeignKey("IntegranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escala");

                    b.Navigation("Instrumento");

                    b.Navigation("Integrante");
                });

            modelBuilder.Entity("Escalouve.Domain.Entities.IntegranteInstrumento", b =>
                {
                    b.HasOne("Escalouve.Domain.Entities.Instrumento", "Instrumento")
                        .WithMany("IntegrantesInstrumentos")
                        .HasForeignKey("InstrumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Escalouve.Domain.Entities.Integrante", "Integrante")
                        .WithMany("IntegrantesInstrumentos")
                        .HasForeignKey("IntegranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrumento");

                    b.Navigation("Integrante");
                });

            modelBuilder.Entity("Escalouve.Domain.Entities.Escala", b =>
                {
                    b.Navigation("Escalados");
                });

            modelBuilder.Entity("Escalouve.Domain.Entities.Instrumento", b =>
                {
                    b.Navigation("IntegrantesInstrumentos");
                });

            modelBuilder.Entity("Escalouve.Domain.Entities.Integrante", b =>
                {
                    b.Navigation("IntegrantesInstrumentos");
                });
#pragma warning restore 612, 618
        }
    }
}
